name: Generate Android APK
on:
  workflow_dispatch:
  push:

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Repair Project
        run: |
          rm -rf android
          flutter create --platforms=android .
      - name: Build APK
        run: flutter build apk --debug
        
